### PR TITLE
tutorial on Docker Machine with the ddcloud driver

### PR DESCRIPTION
**Pull request by bernard357**
this is early start, with a diagram to be validated. textual instructions and screenshots to follow

### CODE REVIEW

**Comment by tintoy** [comment]
Thanks, @bernard357 - that's great!

Any chance we could make the commands to run into text instead of part of the image? I could imaging people wanting to copy / paste the commands to follow along...

**Comment by bernard357** [comment]
Sure @tintoy, following explanations will provide textual commands :-)

**Comment by bernard357** [comment]
@tintoy can you please review the setup page and fix any issue? Thanks

**Comment by tintoy** [comment]
Just one thing - you don't need docker toolbox on Windows if all you want to do is run docker-machine. You can download the latest release from https://github.com/docker/machine/releases

**Comment by bernard357** [comment]
@tintoy the setup page has been updated as per your feedback. Is this enough for you to accept this PR?

**Comment by tintoy** [comment]
Thanks again for doing this :)

**Comment by tintoy** [comment]
@bernard357, I'm considering creating a simple Terraform configuration to include in that document (for the case where people want to quickly get their infrastructure configured so they can follow the tutorial). What do you reckon?

**Comment by bernard357** [comment]
@tintoy sure! any orchestration that can facilitate the life of end-user would be great

**Pull request merged**
