### PR TITLE
be friendly with Windows users

### PR DESCRIPTION
**Pull request by bernard357**
This is a slight update because so many colleagues and clients are still using Windows. We do want them to benefit from Docker Machine on MCP as well, right? Documentation has been updated accordingly, yet this would deserve some test by some real Windows users.

### CODE REVIEW

**Comment by bernard357** [comment]
Adam, let me know if there is any other change required before you accept the pull request :-)

**Comment by tintoy** [comment]
Oops, sorry @bernard357 - I don't know why I never merged this change! I'm going to review it ASAP.

**Comment by tintoy** [comment]
Looks good to me :)

**Comment by tintoy** [comment]
Done. Sorry for the delay!

**Comment by bernard357** [comment]
no pb Adam, thanks for the merge

**Pull request merged**
